#!/bin/bash

# Git
alias git-add-credentials='git config --global credential.helper store'
alias git-remove-credentials='git config --global --unset credential.helper'

alias vim-help='echo -e $(<~/.vim/help.txt) | less -R'
