#!/bin/bash

# Load common aliases
if [[ -f ~/.bash_common_user ]] ; then
  source ~/.bash_common_user
fi

# Load aliases expansion
if [[ -f ~/.bash_aliases_expansion ]] ; then
  source ~/.bash_aliases_expansion
fi
